# Generated by Django 4.2.2 on 2023-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
