# Generated by Django 4.2.2 on 2023-07-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_id_alter_teamleader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='assignedTL',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.teamleader'),
        ),
    ]
