# Generated by Django 4.2.2 on 2023-07-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_member_assignedtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='assignedTL',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.teamleader'),
        ),
    ]
