# Generated by Django 4.2.2 on 2023-07-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_assignedtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=100)),
                ('TeamLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teamleader')),
                ('members', models.ManyToManyField(to='core.member')),
            ],
        ),
    ]
