# Generated by Django 4.2.2 on 2023-07-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_teamleader_project_assignedteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignedTeam',
        ),
        migrations.AddField(
            model_name='project',
            name='TeamLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teamleader'),
        ),
    ]
